language: python

python:
  - 3.7

# command to run tests
script:
  - ./run_tests.sh


before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq  python3-pip python3-setuptools poppler-utils imagemagick tesseract-ocr
- pip3 install stapler
sudo: false

install:
  - pip3 install -r requirements/base.txt
