# Generated by Django 3.1 on 2020-11-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_auto_20201118_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('allow_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NodeX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_ptr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_dr_nodex_related', related_query_name='app_dr_nodexs', to='core.basetreenode')),
                ('policy_x', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statesx', to='app_dr.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_ptr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_dr_node_related', related_query_name='app_dr_nodes', to='core.basetreenode')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='app_dr.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
