# Generated by Django 3.1 on 2020-11-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='allow_delete',
            field=models.BooleanField(default=False),
        ),
    ]
