# Generated by Django 3.1 on 2020-11-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201023_0702'),
        ('app_dr', '0002_policy_allow_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_dr_nodex_related', related_query_name='app_dr_nodexs', to='core.basetreenode')),
                ('policy_x', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statesx', to='app_dr.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
