version: '3.7'
services:
  app:
    image: eugenci/papermerge:1.5.3
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: papermerge_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - media_root:/opt/media
      - broker_queue:/opt/app/queue
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
  db:
    image: postgres:12.3
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
  worker:
    image: eugenci/papermerge-worker:1.5.3
    build:
      context: .
      dockerfile: worker.dockerfile    
    container_name: papermerge_worker
    volumes:
      - media_root:/opt/media
      - broker_queue:/opt/app/queue
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432      
volumes:
  postgres_data:
  broker_queue:
  media_root: