# Generated by Django 3.0.2 on 2020-04-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200419_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsr_code', models.CharField(max_length=16, unique=True)),
                ('pg_catalog', models.CharField(max_length=64)),
                ('pg_short', models.CharField(max_length=64)),
            ],
        ),
    ]
