# Generated by Django 3.0.2 on 2020-04-19 07:46

from django.db import migrations

# https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
# ISO-639-2/T => psql> \dFd (which lists installed dictionaries)
initial_language_dict = {
    'ara': 'arabic',
    'dan': 'danish',
    'nld': 'dutch',
    'eng': 'english',
    'fin': 'finnish',
    'fra': 'french',
    'deu': 'german',
    'hun': 'hungarian',
    'ind': 'indonesian',
    'gle': 'irish',
    'ita': 'italian',
    'lit': 'lithuanian',
    'nep': 'nepali',
    'nor': 'norwegian',
    'por': 'portuguese',
    'ron': 'romanian',
    'rus': 'russian',
    'spa': 'spanish',
    'swe': 'swedish',
    'tam': 'tamil',
    'tur': 'turkish',
}


def insert_language_maps(apps, schema_editor):
    LanguageMap = apps.get_model('core', 'LanguageMap')
    for key, value in initial_language_dict.items():
        lang_map = LanguageMap(
            tsr_code=key,
            pg_short=value,
            pg_catalog=f"pg_catalog.{value}"
        )
        lang_map.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_languagemap'),
    ]

    operations = [
        migrations.RunPython(insert_language_maps),
    ]
