# Generated by Django 3.0.6 on 2020-06-02 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200601_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='KVStore',
            fields=[
                ('key', models.CharField(max_length=200)),
                ('namespace', models.CharField(max_length=1024)),
                ('namespaced_key', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField()),
                ('human_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KVStorePage',
            fields=[
                ('kvstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.KVStore')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Page')),
            ],
            bases=('core.kvstore',),
        ),
        migrations.CreateModel(
            name='KVStoreNode',
            fields=[
                ('kvstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.KVStore')),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BaseTreeNode')),
            ],
            bases=('core.kvstore',),
        ),
    ]
