# Generated by Django 3.0.10 on 2020-09-23 14:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200921_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automate',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.ColoredTag', to='core.Tag', verbose_name='Tags'),
        ),
    ]
