# Generated by Django 3.0.10 on 2020-10-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_document_digest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_orig',
        ),
    ]
