# Generated by Django 3.1 on 2020-11-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201023_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetreenode',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='basetreenode',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
