# Generated by Django 3.1 on 2020-11-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20201113_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetreenode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='basetreenode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
