# Generated by Django 3.1.3 on 2020-11-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20201119_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_by_secret',
            field=models.BooleanField(default=False, help_text='Designates whether the mail import should consider the secret', verbose_name='mail import secret'),
        ),
        migrations.AddField(
            model_name='user',
            name='mail_by_user',
            field=models.BooleanField(default=False, help_text='Designates whether the mail import should consider the email address', verbose_name='mail import user'),
        ),
        migrations.AddField(
            model_name='user',
            name='mail_secret',
            field=models.CharField(blank=True, max_length=150, verbose_name='email secret'),
        ),
    ]
