#!/bin/bash

psql --username "$POSTGRES_USER" <<-EOSQL
     CREATE USER $PMG_DB_USER WITH PASSWORD '$PMG_DB_PASS';
     CREATE DATABASE $PMG_DB_NAME;
     GRANT ALL PRIVILEGES ON DATABASE $PMG_DB_NAME TO $PMG_DB_USER;
EOSQL